# 概述

## 1. 运算符

### 1.1 算术运算符

在 dart 中 ，使用 `/` 两个整数相除是可以得到浮点数的。 `~/` 才是用来除并取整。
```dart

assert(2 + 3 == 5);
assert(2 - 3 == -1);
assert(2 * 3 == 6);
assert(5 / 2 == 2.5); // 结果是一个浮点数
assert(5 ~/ 2 == 2); // 结果是一个整数
assert(5 % 2 == 1); // 取余

```

### 1.2 类型判断运算符

Operator|Meaning|
----|----|
as|类型转换|
is|如果对象是指定类型则返回 true
is!|如果对象是指定类型则返回 false

```dart

// 如果 emp 为 null 或者 不是person类型的对象，会抛出异常
(emp as Person).firstName = 'Bob';

if (emp is Person) {
  // 类型检查
  emp.firstName = 'Bob';
}

```

### 1.3 赋值运算符

可以使用 = 来赋值，同时也可以使用 `??=` 来为值为 `null` 的变量赋值。

```dart

// 将 value 赋值给 a (Assign value to a)
a = value;
// 当且仅当 b 为 null 时才赋值
b ??= value;

```

### 1.4 级联运算符

级联运算符（`..`）可以让你在同一个对象上连续调用多个对象的变量或方法。

```dart
querySelector('#confirm') // 获取对象 (Get an object).
  ..text = 'Confirm' // 使用对象的成员 (Use its members).
  ..classes.add('important')
  ..onClick.listen((e) => window.alert('Confirmed!'));

var button = querySelector('#confirm');
button.text = 'Confirm';
button.classes.add('important');
button.onClick.listen((e) => window.alert('Confirmed!'));

```

> 严格来说 `..` 级联操作并非一个运算符而是 Dart 的特殊语法。

### 1.5 条件访问运算符

条件访问运算符 `?.`, 例如 foo?.bar，如果 foo 为 null 则返回 null ，否则返回 bar

## 2. 流程控制

### 2.1 switch case

`switch` 语句在 Dart 中使用 `==` 来比较整数、字符串或编译时常量，比较的两个对象必须是同一个类型且不能是子类并且没有重写 == 操作符

```dart
var command = 'OPEN';
switch (command) {
  case 'CLOSED':
    executeClosed();
    break;
  case 'PENDING':
    executePending();
    break;
  default:
    executeUnknown();
}
```
`case`语句后为空的语句，可以直接 fall-through; 

`case`语句不为空，要么使用 `break` 跳出 switch；
要么使用 `continue` 语句配合 lable；

```dart
var command = 'CLOSED';
switch (command) {
  case 'CLOSED':
    executeClosed();
    continue nowClosed;
 
  // 继续执行标签为 nowClosed 的 case 子句。
  nowClosed:
  case 'NOW_CLOSED':
    // case 条件值为 CLOSED 和 NOW_CLOSED 时均会执行该语句。
    executeNowClosed();
    break;
}
```

### 2.2 assert 断言

在开发环境，可以在条件表达式为 false 时使用 - assert(条件, 可选信息); - 语句来打断代码的执行。

```dart

assert(text != null);

```
在生产环境代码中，断言会被忽略，与此同时传入 assert 的参数不被判断

## 3. 异常

`Dart` 代码可以抛出和捕获异常。异常表示一些未知的错误情况，如果异常没有捕获则会被抛出从而导致抛出异常的代码终止执行.

`Dart` 提供了 `Exception` 和 `Error` 两种类型的异常以及它们一系列的子类，你也可以定义自己的异常类型。但是在 Dart 中可以将任何非 `null` 对象作为异常抛出而不局限于 Exception 或 Error 类型.

**抛出异常**

```dart

throw FormatException("Excepted at leasr 1 section");

// 可以抛出任何非空对象

throw "out of memory";
```

**捕获异常**

使用 `on` 或 `catch` 来捕获异常，使用 `on` 来指定异常类型，使用 `catch` 来捕获异常对象，两者可同时使用。

你可以为 catch 方法指定两个参数，第一个参数为抛出的异常对象，第二个参数为栈信息对象：

关键字 rethrow 可以将捕获的异常再次抛出
```dart
try {
  breedMoreLlamas();
} on OutOfLlamasException {   // on 匹配异常类型
  // 指定异常
  buyMoreLlamas();
} on Exception catch (e) {    // catch 捕获异常对象
  // 其它类型的异常
  print('Unknown exception: $e');
} catch (e , s) {                  // 不指定类型，匹配所有异常 , 第一个参数为抛出的异常对象，第二个参数为栈信息
  // // 不指定类型，处理其它全部
  print('Something really unknown: $e');

  rethrow;       //再次抛出
}
```

**finally**

可以使用 `finally` 语句来包裹确保不管有没有异常都执行代码，如果没有指定 `catch` 语句来捕获异常，则在执行完 `finally` 语句后再抛出异常：

```dart
try {
  breedMoreLlamas();
} catch (e) {
  print('Error: $e'); // 先处理异常。
} finally {
  cleanLlamaStalls(); // 然后清理。
}
```


