Kotlin 中所有异常类继承自 Throwable 类。 每个异常都有消息、堆栈回溯信息以及可选的原因。

```kotlin 
try {
    // 一些代码
} catch (e: SomeException) {
    // 处理程序
} finally {
    // 可选的 finally 块
}
```

- Try 是一个表达式

try 是一个表达式，意味着它可以有一个返回值： 

```kotlin 
val a: Int? = try { input.toInt() } catch (e: NumberFormatException) { null }