# try语句块和异常处理

异常处理机制为程序中异常检测和异常处理这两部分的协作提供支持。


- **throw语句块**，异常检测部分使用throw表达式来表示它遇到无法处理的问题，我们说throw引发了异常。

- **try语句块**，异常处理部分使用try语句块处理异常。try语句块中代码抛出的异常通常会被某个catch子句捕获并处理。成为异常处理代码

- 异常类，用于在throw表达式和相关的catch子句之间传递异常的具体信息。

## 1. throw表达式

程序的异常检测部分使用throw表达式引发一个异常。

```c++
if(error){
    throw runtime_error("发生一个异常");
}

```
抛出异常将终止当前函数，并把控制权转移给能处理异常的代码。

## 2.try语句块

```c++
try{
    statement
} catch (exception-declaration) {
    handler-statement
} catch (exception-declaration) {
    handler-statement
}

```

### 异常处理的过程

1. 当异常被抛出时，首先搜索抛出该异常的函数，如果匹配可以处理该异常的catch子句，则将异常交由catch语句处理。

2. 如果没找到匹配的catch子句，终止该函数，并在调用该函数的函数中继续查找。

3. 以此类推，沿着程序的调用链逐层回退，直到找到合适类型的catch字句为止。

4. 如果最终还是没有找到任何匹配的catch子句，程序转到名为`terminate`的标准库函数。执行到`terminate`函数将导致程序非正常退出。

## 3.标准异常

C++标准库定义了一组类，用于报告标准库函数遇到的问题。

分别定义在4个头文件中：

- `exception` ： 头文件定义最通用的异常类`exception`。它只报告异常的发生，不提供任何额外的信息。

- `stdexcept` : 定义几种常用的异常类
  

stdexcept异常类|描述
----|----
exception|最常见的问题
runtime_error|只有在运行时才能检测出的问题
range_error|运行时错误：生成的结果超出了有意义的范围
overflow_error|运行时错误：计算上溢
underflow_error|运行时错误：计算下溢
logic_error|程序逻辑错误
domain_error|逻辑错误：参数对应的结果值不存在
invalid_argument|逻辑错误：无效参数
length_error|逻辑错误：试图创建一个超出该类型最大长度的对象
out_of_range|逻辑错误：使用一个超出有效范围的值

- `new`头文件定义了`bad_alloc`类型

- `type_info`头文件定义了`bad_cast`异常类型。

我们只能默认初始化的方法是初始化 `exception`,`bad_alloc`和`bad_cast`对象，不允许为这些对象提供初值。





